src/controllers/addons.py
from flask import Blueprint, Response, redirect, render_template, request, url_for, current_app
from random import randbytes
from datetime import datetime

from src.models import db, dbs, Badge, User, Role, Addon
from src.auth import login_user, admin_required, logout_user, current_user
from src.gateways import Gateways
from src.plugins import Plugins
from src.addons import Addons

import os
import sys
import time
import threading

bp = Blueprint('addons', __name__, url_prefix="/addons")

# Restart the server when new gateways or plugins are added
# Needed to fix after start blueprint usage
def restart():
    def thread():
        time.sleep(1)
        # 
        os.execv(sys.executable, [sys.executable] + sys.argv)
    
    threading.Thread(target=thread).start()
    
    return "The server is restarting... You will be redirected in 5s<script>setTimeout(() => window.location.href = '/', 5000)</script>"

@bp.route('/')
@admin_required
def index():
    addons = dbs.execute(db.select(Addon)).scalars().all()
    return render_template('addons/index.html', addons=addons)

@bp.route('/import', methods=["GET", "POST"])
@admin_required
def import_():

    if request.method == "POST":
        git_url = request.form["git_url"]
        Addons.import_new(git_url, current_app)

        return restart()        

    return render_template('addons/import.html')

@bp.route('/update/<addon_uid>', methods=["POST"])
@admin_required
def update(addon_uid):
    Addons.update(addon_uid)
    return restart()

@bp.route('/delete/<addon_uid>', methods=['POST'])
@admin_required
def delete(addon_uid):
    Addons.remove(addon_uid)
    return redirect(url_for('addons.index'))

templates/addons/import.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
    <h1 class="mb-4">Import addon</h1>

    {% if error %}
        <div class="alert alert-danger fw-bold">{{ error }}</div>
    {% endif %}

    <form method="post" class="row g-3">

        <div class="col-md-6">
            <label for="guest_name" class="form-label">Git URL :</label>
            <input type="text" class="form-control" id="git_url" name="git_url" placeholder="https://github.com/user/repo.git | git@github.com:user/repo.git ">
        </div>

        <div class="col-12">
            <button type="submit" class="btn btn-success">Add</button>
            <a href="{{ url_for('addons.index') }}" class="btn btn-secondary ms-2">Back</a>
        </div>
    </form>
</div>
{% endblock %}

templates/addons/index.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="m-0">Addons</h1>
    <a href="{{ url_for('addons.import_') }}" class="btn btn-success">
        <i class="bi bi-plus-lg"></i> Import
    </a>
</div>

<table class="table table-striped align-middle">
    <thead class="table-light">
        <tr>
            <th>UID</th>
            <th>Git URL</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for addon in addons %}
        <tr>
            <td>{{ addon['uid'] }}</td>
            <td>{{ addon['git_url'] }}</td>
            <td class="d-flex gap-1">
                <form action="{{ url_for('addons.update', addon_uid=addon['uid']) }}" method="post">
                    <button class="btn btn-sm btn-warning" title="Update" data-bs-toggle="tooltip" data-bs-title="Update">
                        <i class="bi bi-arrow-clockwise"></i>
                    </button>
                </form>
                <form method="POST" action="{{ url_for('addons.delete', addon_uid=addon['uid']) }}" onsubmit="return confirm('Are you sure you want to delete this addon ?');">
                    <button type="submit" class="btn btn-sm btn-danger" data-bs-toggle="tooltip" data-bs-title="Delete">
                        <i class="bi bi-trash-fill"></i>
                    </button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}